USE SUSUSHISHI
GO

-- Index
CREATE PROCEDURE getUserIdByAccount 
    @USERNAME NVARCHAR(50)
AS
BEGIN
    SELECT 
		AC.PASSWORD,
        CASE 
            WHEN AC.CUSTOMER_ID IS NULL THEN AC.EMPLOYEE_ID
            ELSE AC.CUSTOMER_ID 
        END AS Id,
        AC.ROLE,
        CASE 
            WHEN AC.CUSTOMER_ID IS NULL THEN E.FULL_NAME
            ELSE C.FULL_NAME
        END AS Name
    FROM ACCOUNT AC
    LEFT JOIN EMPLOYEE E ON AC.EMPLOYEE_ID = E.EMPLOYEE_ID
    LEFT JOIN CUSTOMER C ON AC.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE AC.USERNAME = @USERNAME 
END
GO

SELECT * FROM ACCOUNT
WHERE USERNAME = 'christie95'

INSERT INTO ACCOUNT



SELECT * FROM ACCOUNT
SET STATISTICS TIME ON
GO
EXEC getUserIdByAccount 'juan95'
GO
SET STATISTICS TIME OFF
CREATE UNIQUE INDEX IDX_ACCOUNT_USERNAME ON ACCOUNT(USERNAME) 
DROP INDEX ACCOUNT.IDX_ACCOUNT_USERNAME

GO
-- Idx2
CREATE PROCEDURE getInvoiceByPhone
    @CUSTOMER_PHONE VARCHAR(15) = NULL,
    @DATE DATE = NULL
AS
BEGIN
    -- Nếu có CUSTOMER_PHONE và DATE d?u NULL, tr? v? r?ng
    IF @CUSTOMER_PHONE IS NULL AND @DATE IS NULL
    BEGIN
        -- Tr? v? b?ng tr?ng cho k?t qu? hóa don
        SELECT TOP 0 
            I.INVOICE_ID, 
            I.FINAL_AMOUNT, 
            I.DISCOUNT_AMOUNT, 
            I.ISSUE_DATE, 
            I.ISSUE_TIME
        FROM INVOICE I;

        -- Tr? v? b?ng tr?ng cho danh sách món an
        SELECT TOP 0 
            I.INVOICE_ID,	
            OD.DISH_ID,
            OD.QUANTITY AS AMOUNT,
            D.DISH_NAME,
            D.DISH_PRICE
        FROM INVOICE I
        LEFT JOIN ORDER_DISH OD ON I.ORDER_ID = OD.ORDER_ID
        LEFT JOIN DISH D ON D.DISH_ID = OD.DISH_ID;

        RETURN;
    END;

    -- Bi?n d? luu Invoice ID duy nh?t
    DECLARE @InvoiceId CHAR(7);

    -- Tìm khách hàng dựa trên số điện thoại
    DECLARE @CustomerId CHAR(7) = (
        SELECT CUSTOMER_ID 
        FROM CUSTOMER
        WHERE PHONE_NUMBER = @CUSTOMER_PHONE
    );

    -- Lấy hóa don phù hợp nhất dựa trên CUSTOMER_ID và DATE
    SELECT I.INVOICE_ID, I.FINAL_AMOUNT, I.DISCOUNT_AMOUNT, I.ISSUE_DATE, I.ISSUE_TIME
    FROM INVOICE I
    LEFT JOIN [ORDER_] O ON O.ORDER_ID = I.ORDER_ID
    WHERE 
        (@CustomerId IS NULL OR O.CUSTOMER_ID = @CustomerId)
        AND (@DATE IS NULL OR CAST(I.ISSUE_DATE AS DATE) = @DATE)
    ORDER BY I.ISSUE_DATE DESC, I.ISSUE_TIME DESC;

    -- Danh sách món an của các hóa don
    SELECT 
        I.INVOICE_ID,
        OD.DISH_ID,
        OD.QUANTITY AS AMOUNT,
        D.DISH_NAME,
        D.DISH_PRICE
    FROM INVOICE I
    LEFT JOIN ORDER_DISH OD ON I.ORDER_ID = OD.ORDER_ID
    LEFT JOIN DISH D ON D.DISH_ID = OD.DISH_ID
    WHERE 
        (@CustomerId IS NULL OR I.ORDER_ID IN (
            SELECT ORDER_ID FROM [ORDER_] WHERE CUSTOMER_ID = @CustomerId
        ))
        AND (@DATE IS NULL OR CAST(I.ISSUE_DATE AS DATE) = @DATE)
    ORDER BY I.INVOICE_ID, D.DISH_NAME;
END;
GO

CREATE UNIQUE INDEX IDX_CUSTOMER_PHONENUMBER ON CUSTOMER(PHONE_NUMBER)
DROP INDEX CUSTOMER.IDX_CUSTOMER_PHONENUMBER
SELECT * FROM CUSTOMER WHERE PHONE_NUMBER = '910945519'

SET STATISTICS TIME ON
EXEC getInvoiceByPhone @CUSTOMER_PHONE = '910945519'
SET STATISTICS TIME OFF


EXEC createCustomerCardForNew N'TẤN lộc', '012345679', 'loc123@gmail.com', '975748891772841', N'Nam', NULL 

@fullName NVARCHAR(50),
    @phoneNumber CHAR(15),
    @email CHAR(50),
    @identityCard CHAR(15),
    @gender NVARCHAR(5),
    @employeeId CHAR(7)

-- IDX3:
CREATE NONCLUSTERED INDEX IX_EMPLOYEE_COVERAGE
ON EMPLOYEE(DEPARTMENT_ID)
INCLUDE (EMPLOYEE_ID, FULL_NAME, DATE_OF_BIRTH, GENDER, SALARY, 
         START_DATE_WORK, TERMINATION_DATE)
DROP INDEX EMPLOYEE.IX_EMPLOYEE_COVERAGE 

SELECT * FROM DEPARTMENT

SELECT * 
FROM EMPLOYEE E 
JOIN DEPARTMENT D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
WHERE D.BRANCH_ID = 'B010'

EXEC addResource 'B003', 'Hello', 'Nam', '05-12-2004', '1-1-2020', 'D015', '123'