USE master
GO
IF DB_ID('SUSHI_RESTAURANT') IS NOT NULL
	DROP DATABASE SUSHI_RESTAURANT
GO 

CREATE DATABASE SUSHI_RESTAURANT
GO
USE SUSHI_RESTAURANT
GO


CREATE TABLE CARD_TYPE
(
	TYPE NVARCHAR(10), -- GOLD, SILVER, MEMBERSHIP
	DISCOUNT_AMOUNT FLOAT --SỐ PHẦN TRĂM

	CONSTRAINT PK_CARD_TYPE
	PRIMARY KEY (TYPE)
)
GO
CREATE TABLE AREA
(
	AREA_ID VARCHAR(3), --MÃ SỐ 001, 002
	AREA_NAME NVARCHAR(40) -- THÀNH PHỐ HỒ CHÍ MINH

	CONSTRAINT PK_AREA
	PRIMARY KEY (AREA_ID)
)
GO
CREATE TABLE CUSTOMER
(
	CUSTOMER_ID VARCHAR(5), -- MÃ SỐ 00001 - 99999 (NHIỀU KHÁCH HÀNG LẮM)
	FULL_NAME NVARCHAR(50),
	PHONE_NUMBER CHAR(10), --SDT 10 SỐ
	EMAIL VARCHAR(40), 
	IDENTITY_CARD CHAR(12), -- CCCD 12 SỐ
	GENDER NVARCHAR(4) --NAM/NỮ

	CONSTRAINT PK_CUSTOMER
	PRIMARY KEY (CUSTOMER_ID)
)
GO
CREATE TABLE MENU_CATEGORY
(
	CATEGORY_ID CHAR(3), -- 001, 002,..
	CATEGORY_NAME NVARCHAR(30)

	CONSTRAINT PK_MENU_CATEGORY
	PRIMARY KEY (CATEGORY_ID)
)
GO
CREATE TABLE DISH
(
	DISH_ID CHAR(3), -- TỐI ĐA CÓ 999 MÓN THOI
	DISH_NAME NVARCHAR (30),
	DISH_PRICE INT, -- ĐƠN VỊ VND 
	CATEGORY_ID CHAR(3)

	CONSTRAINT PK_DISH
	PRIMARY KEY (DISH_ID),

	CONSTRAINT FK_DISH_MENUCATGORY
	FOREIGN KEY (CATEGORY_ID)
	REFERENCES MENU_CATEGORY
)