/*
DROP database [susushishi1]
go
CREATE DATABASE [susushishi1]
GO
USE [susushishi1]
GO
*/
GO
ALTER DATABASE [susushishi1] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [susushishi1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [susushishi1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [susushishi1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [susushishi1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [susushishi1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [susushishi1] SET ARITHABORT OFF 
GO
ALTER DATABASE [susushishi1] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [susushishi1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [susushishi1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [susushishi1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [susushishi1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [susushishi1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [susushishi1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [susushishi1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [susushishi1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [susushishi1] SET  ENABLE_BROKER 
GO
ALTER DATABASE [susushishi1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [susushishi1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [susushishi1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [susushishi1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [susushishi1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [susushishi1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [susushishi1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [susushishi1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [susushishi1] SET  MULTI_USER 
GO
ALTER DATABASE [susushishi1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [susushishi1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [susushishi1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [susushishi1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [susushishi1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [susushishi1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [susushishi1] SET QUERY_STORE = ON
GO
ALTER DATABASE [susushishi1] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [susushishi1]
GO
/****** Object:  Table [dbo].[ACCOUNT]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[ACCOUNT_ID] [nvarchar](7) NOT NULL,
	[USER_NAME] [nvarchar](50) NOT NULL,
	[PASSWORD] [varchar](100) NOT NULL,
	[ROLE] [nvarchar](20) NOT NULL,
	[CUSTOMER_ID] [char](6) NULL,
	[EMPLOYEE_ID] [char](7) NULL,
 CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AREA]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AREA](
	[AREA_ID] [char](3) NOT NULL,
	[AREA_NAME] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_AREA] PRIMARY KEY CLUSTERED 
(
	[AREA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BRANCH_RATING]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BRANCH_RATING](
	[RATING_ID] [char](7) NOT NULL,
	[SERVICE_RATING] [int] NOT NULL,
	[LOCATION_RATING] [int] NOT NULL,
	[PRICE_RATING] [int] NOT NULL,
	[DISH_QUALITY_RATING] [int] NOT NULL,
	[ENVIRONMENT_RATING] [int] NOT NULL,
	[COMMENT] [nvarchar](100) NOT NULL,
	[BRANCH_ID] [char](4) NULL,
	[RATING_DATE] [date] NOT NULL,
	[INVOICE_ID] [char](7) NULL,
 CONSTRAINT [PK_BRANCH_RATING] PRIMARY KEY CLUSTERED 
(
	[RATING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CARD_TYPE]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARD_TYPE](
	[TYPE] [nvarchar](30) NOT NULL,
	[DISCOUNT_AMOUNT] [float] NOT NULL,
 CONSTRAINT [PK_CARD_TYPE] PRIMARY KEY CLUSTERED 
(
	[TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CART]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CART](
	[CART_ID] [char](6) NOT NULL,
	[BRANCH_ID] [char](4) NOT NULL,
	[CUSTOMER_ID] [char](6) NOT NULL,
 CONSTRAINT [PK_CART] PRIMARY KEY CLUSTERED 
(
	[CART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CART_DISH]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CART_DISH](
	[DISH_ID] [char](4) NOT NULL,
	[CART_ID] [char](6) NOT NULL,
	[QUANTITY] [int] NULL,
 CONSTRAINT [PK_CART_DISH] PRIMARY KEY CLUSTERED 
(
	[DISH_ID] ASC,
	[CART_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[CUSTOMER_ID] [char](6) NOT NULL,
	[FULL_NAME] [nvarchar](50) NOT NULL,
	[PHONE_NUMBER] [char](10) NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[IDENTITY_CARD] [char](12) NULL,
	[GENDER] [nvarchar](4) NOT NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DELIVERY_ORDER]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DELIVERY_ORDER](
	[DORDER_ID] [char](7) NOT NULL,
	[DATE_DELIVERY] [date] NOT NULL,
	[TIME_DELIVERY] [time](7) NOT NULL,
 CONSTRAINT [PK_DELIVERY_ORDER] PRIMARY KEY CLUSTERED 
(
	[DORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTMENT]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT](
	[DEPARTMENT_ID] [char](4) NOT NULL,
	[DEPARTMENT_NAME] [nvarchar](50) NOT NULL,
	[BRANCH_ID] [char](4) NULL,
 CONSTRAINT [PK_DEPARTMENT_1] PRIMARY KEY CLUSTERED 
(
	[DEPARTMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DISH]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISH](
	[DISH_ID] [char](4) NOT NULL,
	[DISH_NAME] [nvarchar](50) NOT NULL,
	[DISH_PRICE] [int] NOT NULL,
	[CATEGORY_ID] [char](4) NULL,
	[DISH_URL] [varchar](100) NULL,
 CONSTRAINT [PK_DISH] PRIMARY KEY CLUSTERED 
(
	[DISH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DISH_AVAILABLE]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISH_AVAILABLE](
	[BRANCH_ID] [char](4) NOT NULL,
	[DISH_ID] [char](4) NOT NULL,
	[IS_AVAILABLE] [bit] NOT NULL,
	[ABLE_DELIVERIED] [bit] NOT NULL,
 CONSTRAINT [PK_DISH_AVAILABLE] PRIMARY KEY CLUSTERED 
(
	[BRANCH_ID] ASC,
	[DISH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EMPLOYEE_ID] [char](7) NOT NULL,
	[FULL_NAME] [nvarchar](50) NOT NULL,
	[DATE_OF_BIRTH] [date] NOT NULL,
	[GENDER] [nvarchar](4) NOT NULL,
	[SALARY] [int] NOT NULL,
	[START_DATE] [date] NOT NULL,
	[TERMINATION_DATE] [date] NULL,
	[DEPARTMENT_ID] [char](4) NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICE]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE](
	[INVOICE_ID] [char](7) NOT NULL,
	[TOTAL_AMOUNT] [int] NOT NULL,
	[DISCOUNT] [float] NOT NULL,
	[ISSUE_DATE] [date] NOT NULL,
	[ORDER_ID] [char](7) NULL,
 CONSTRAINT [PK_INVOICE] PRIMARY KEY CLUSTERED 
(
	[INVOICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBERSHIP_CARD]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBERSHIP_CARD](
	[CARD_ID] [char](7) NOT NULL,
	[CARD_TYPE] [nvarchar](30) NULL,
	[CUSTOMER_ID] [char](6) NULL,
	[DATE_ISSUED] [date] NOT NULL,
	[EMPLOYEE_ID] [char](7) NULL,
	[POINTS] [int] NOT NULL,
	[CARD_STATUS] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_MEMBERSHIP_CARD] PRIMARY KEY CLUSTERED 
(
	[CARD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MENU_CATEGORY]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MENU_CATEGORY](
	[CATEGORY_ID] [char](4) NOT NULL,
	[CATEGORY_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MENU_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OFFLINE_ORDER]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OFFLINE_ORDER](
	[OFORDER_ID] [char](7) NOT NULL,
	[TABLE_NUMBER] [int] NULL,
	[EMPLOYEE_ID] [char](7) NULL,
	[EMPLOYEE_RATING] [int] NOT NULL,
	[BRANCH_ID] [char](4) NULL,
 CONSTRAINT [PK_OFFLINE_ORDER] PRIMARY KEY CLUSTERED 
(
	[OFORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONLINE_ACCESS_HISTORY]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONLINE_ACCESS_HISTORY](
	[DATE_ACCESSED] [date] NOT NULL,
	[TIME_ACCESSED] [time](7) NOT NULL,
	[CUSTOMER_ID] [char](6) NOT NULL,
	[ACCESS_DURATION] [time](7) NOT NULL,
 CONSTRAINT [PK_ONLINE_ACCESS_HISTORY] PRIMARY KEY CLUSTERED 
(
	[DATE_ACCESSED] ASC,
	[TIME_ACCESSED] ASC,
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ONLINE_ORDER]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ONLINE_ORDER](
	[OORDER_ID] [char](7) NOT NULL,
	[ARRIVAL_DATE] [date] NOT NULL,
	[ARRIVAL_TIME] [time](7) NOT NULL,
	[TABLE_NUMBER] [int] NULL,
	[CUSTOMER_QUANTITY] [int] NOT NULL,
	[BRANCH_ID] [char](4) NULL,
 CONSTRAINT [PK_ONLINE_ORDER] PRIMARY KEY CLUSTERED 
(
	[OORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDER]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER](
	[ORDER_ID] [char](7) NOT NULL,
	[ORDER_DATE] [date] NOT NULL,
	[BRANCH_ID] [char](4) NULL,
	[CUSTOMER_ID] [char](6) NULL,
	[ORDER_TYPE] [nvarchar](20) NOT NULL,
	[ORDER_TIME] [time](7) NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDER_DISH]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER_DISH](
	[ORDER_ID] [char](7) NOT NULL,
	[DISH_ID] [char](4) NOT NULL,
	[QUANTITY] [int] NOT NULL,
 CONSTRAINT [PK_ORDER_DISH] PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC,
	[DISH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESTAURANT_BRANCH]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESTAURANT_BRANCH](
	[BRANCH_ID] [char](4) NOT NULL,
	[BRANCH_PHONE] [char](10) NOT NULL,
	[BRANCH_NAME] [nvarchar](50) NOT NULL,
	[BRANCH_ADDRESS] [nvarchar](70) NOT NULL,
	[OPEN_TIME] [time](7) NOT NULL,
	[CLOSE_TIME] [time](7) NOT NULL,
	[CAR_PARK] [varchar](3) NOT NULL,
	[MOTORBIKE_PARK] [varchar](3) NOT NULL,
	[MANAGER_ID] [char](7) NULL,
	[AREA_ID] [char](3) NULL,
 CONSTRAINT [PK_RESTAURANT_BRANCH] PRIMARY KEY CLUSTERED 
(
	[BRANCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLE_]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLE_](
	[TABLE_NUM] [int] NOT NULL,
	[BRANCH_ID] [char](4) NOT NULL,
	[TABLE_STATUS] [nvarchar](50) NOT NULL,
	[SEAT_AVILABLE] [int] NOT NULL,
 CONSTRAINT [PK_TABLE] PRIMARY KEY CLUSTERED 
(
	[TABLE_NUM] ASC,
	[BRANCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WORK_HISTORY]    Script Date: 05/12/2024 20:04:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORK_HISTORY](
	[BRANCH_START_DATE] [date] NOT NULL,
	[BRANCH_END_DATE] [date] NULL,
	[EMPLOYEE_ID] [char](7) NOT NULL,
	[BRANCH_ID] [char](4) NULL,
 CONSTRAINT [PK_WORK_HISTORY] PRIMARY KEY CLUSTERED 
(
	[BRANCH_START_DATE] ASC,
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_ACCOUNT_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_ACCOUNT_CUSTOMER]
GO
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_ACCOUNT_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_ACCOUNT_EMPLOYEE]
GO
ALTER TABLE [dbo].[BRANCH_RATING]  WITH CHECK ADD  CONSTRAINT [FK_BRANCH_RATING_INVOICE] FOREIGN KEY([INVOICE_ID])
REFERENCES [dbo].[INVOICE] ([INVOICE_ID])
GO
ALTER TABLE [dbo].[BRANCH_RATING] CHECK CONSTRAINT [FK_BRANCH_RATING_INVOICE]
GO
ALTER TABLE [dbo].[BRANCH_RATING]  WITH CHECK ADD  CONSTRAINT [FK_BRANCH_RATING_RESTAURANT_BRANCH] FOREIGN KEY([BRANCH_ID])
REFERENCES [dbo].[RESTAURANT_BRANCH] ([BRANCH_ID])
GO
ALTER TABLE [dbo].[BRANCH_RATING] CHECK CONSTRAINT [FK_BRANCH_RATING_RESTAURANT_BRANCH]
GO
ALTER TABLE [dbo].[CART]  WITH CHECK ADD  CONSTRAINT [FK_CART_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[CART] CHECK CONSTRAINT [FK_CART_CUSTOMER]
GO
ALTER TABLE [dbo].[CART]  WITH CHECK ADD  CONSTRAINT [FK_CART_RESTAURANT_BRANCH] FOREIGN KEY([BRANCH_ID])
REFERENCES [dbo].[RESTAURANT_BRANCH] ([BRANCH_ID])
GO
ALTER TABLE [dbo].[CART] CHECK CONSTRAINT [FK_CART_RESTAURANT_BRANCH]
GO
ALTER TABLE [dbo].[CART_DISH]  WITH CHECK ADD  CONSTRAINT [FK_CART_DISH_CART] FOREIGN KEY([CART_ID])
REFERENCES [dbo].[CART] ([CART_ID])
GO
ALTER TABLE [dbo].[CART_DISH] CHECK CONSTRAINT [FK_CART_DISH_CART]
GO
ALTER TABLE [dbo].[CART_DISH]  WITH CHECK ADD  CONSTRAINT [FK_CART_DISH_DISH] FOREIGN KEY([DISH_ID])
REFERENCES [dbo].[DISH] ([DISH_ID])
GO
ALTER TABLE [dbo].[CART_DISH] CHECK CONSTRAINT [FK_CART_DISH_DISH]
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTMENT_RESTAURANT_BRANCH] FOREIGN KEY([BRANCH_ID])
REFERENCES [dbo].[RESTAURANT_BRANCH] ([BRANCH_ID])
GO
ALTER TABLE [dbo].[DEPARTMENT] CHECK CONSTRAINT [FK_DEPARTMENT_RESTAURANT_BRANCH]
GO
ALTER TABLE [dbo].[DISH]  WITH CHECK ADD  CONSTRAINT [FK_DISH_MENU_CATEGORY] FOREIGN KEY([CATEGORY_ID])
REFERENCES [dbo].[MENU_CATEGORY] ([CATEGORY_ID])
GO
ALTER TABLE [dbo].[DISH] CHECK CONSTRAINT [FK_DISH_MENU_CATEGORY]
GO
ALTER TABLE [dbo].[DISH_AVAILABLE]  WITH CHECK ADD  CONSTRAINT [FK_DISH_AVAILABLE_DISH] FOREIGN KEY([DISH_ID])
REFERENCES [dbo].[DISH] ([DISH_ID])
GO
ALTER TABLE [dbo].[DISH_AVAILABLE] CHECK CONSTRAINT [FK_DISH_AVAILABLE_DISH]
GO
ALTER TABLE [dbo].[DISH_AVAILABLE]  WITH CHECK ADD  CONSTRAINT [FK_DISH_AVAILABLE_RESTAURANT_BRANCH] FOREIGN KEY([BRANCH_ID])
REFERENCES [dbo].[RESTAURANT_BRANCH] ([BRANCH_ID])
GO
ALTER TABLE [dbo].[DISH_AVAILABLE] CHECK CONSTRAINT [FK_DISH_AVAILABLE_RESTAURANT_BRANCH]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_DEPARTMENT] FOREIGN KEY([DEPARTMENT_ID])
REFERENCES [dbo].[DEPARTMENT] ([DEPARTMENT_ID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_DEPARTMENT]
GO
ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_ORDER] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ORDER] ([ORDER_ID])
GO
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK_INVOICE_ORDER]
GO
ALTER TABLE [dbo].[MEMBERSHIP_CARD]  WITH CHECK ADD  CONSTRAINT [FK_MEMBERSHIP_CARD_CARD_TYPE] FOREIGN KEY([CARD_TYPE])
REFERENCES [dbo].[CARD_TYPE] ([TYPE])
GO
ALTER TABLE [dbo].[MEMBERSHIP_CARD] CHECK CONSTRAINT [FK_MEMBERSHIP_CARD_CARD_TYPE]
GO
ALTER TABLE [dbo].[MEMBERSHIP_CARD]  WITH CHECK ADD  CONSTRAINT [FK_MEMBERSHIP_CARD_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[MEMBERSHIP_CARD] CHECK CONSTRAINT [FK_MEMBERSHIP_CARD_CUSTOMER]
GO
ALTER TABLE [dbo].[MEMBERSHIP_CARD]  WITH CHECK ADD  CONSTRAINT [FK_MEMBERSHIP_CARD_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[MEMBERSHIP_CARD] CHECK CONSTRAINT [FK_MEMBERSHIP_CARD_EMPLOYEE]
GO
ALTER TABLE [dbo].[OFFLINE_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_OFFLINE_ORDER_EMPLOYEE1] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[OFFLINE_ORDER] CHECK CONSTRAINT [FK_OFFLINE_ORDER_EMPLOYEE1]
GO
ALTER TABLE [dbo].[OFFLINE_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_OFFLINE_ORDER_TABLE_] FOREIGN KEY([TABLE_NUMBER], [BRANCH_ID])
REFERENCES [dbo].[TABLE_] ([TABLE_NUM], [BRANCH_ID])
GO
ALTER TABLE [dbo].[OFFLINE_ORDER] CHECK CONSTRAINT [FK_OFFLINE_ORDER_TABLE_]
GO
ALTER TABLE [dbo].[ONLINE_ACCESS_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_ONLINE_ACCESS_HISTORY_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[ONLINE_ACCESS_HISTORY] CHECK CONSTRAINT [FK_ONLINE_ACCESS_HISTORY_CUSTOMER]
GO
ALTER TABLE [dbo].[ONLINE_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ONLINE_ORDER_TABLE_] FOREIGN KEY([TABLE_NUMBER], [BRANCH_ID])
REFERENCES [dbo].[TABLE_] ([TABLE_NUM], [BRANCH_ID])
GO
ALTER TABLE [dbo].[ONLINE_ORDER] CHECK CONSTRAINT [FK_ONLINE_ORDER_TABLE_]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_CUSTOMER]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_DELIVERY_ORDER1] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[DELIVERY_ORDER] ([DORDER_ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_DELIVERY_ORDER1]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_OFFLINE_ORDER] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[OFFLINE_ORDER] ([OFORDER_ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_OFFLINE_ORDER]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ONLINE_ORDER] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ONLINE_ORDER] ([OORDER_ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_ONLINE_ORDER]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_RESTAURANT_BRANCH] FOREIGN KEY([BRANCH_ID])
REFERENCES [dbo].[RESTAURANT_BRANCH] ([BRANCH_ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_RESTAURANT_BRANCH]
GO
ALTER TABLE [dbo].[ORDER_DISH]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_DISH_DISH] FOREIGN KEY([DISH_ID])
REFERENCES [dbo].[DISH] ([DISH_ID])
GO
ALTER TABLE [dbo].[ORDER_DISH] CHECK CONSTRAINT [FK_ORDER_DISH_DISH]
GO
ALTER TABLE [dbo].[ORDER_DISH]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_DISH_ORDER] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ORDER] ([ORDER_ID])
GO
ALTER TABLE [dbo].[ORDER_DISH] CHECK CONSTRAINT [FK_ORDER_DISH_ORDER]
GO
ALTER TABLE [dbo].[RESTAURANT_BRANCH]  WITH CHECK ADD  CONSTRAINT [FK_RESTAURANT_BRANCH_AREA] FOREIGN KEY([AREA_ID])
REFERENCES [dbo].[AREA] ([AREA_ID])
GO
ALTER TABLE [dbo].[RESTAURANT_BRANCH] CHECK CONSTRAINT [FK_RESTAURANT_BRANCH_AREA]
GO
ALTER TABLE [dbo].[RESTAURANT_BRANCH]  WITH CHECK ADD  CONSTRAINT [FK_RESTAURANT_BRANCH_EMPLOYEE] FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[RESTAURANT_BRANCH] CHECK CONSTRAINT [FK_RESTAURANT_BRANCH_EMPLOYEE]
GO
ALTER TABLE [dbo].[TABLE_]  WITH CHECK ADD  CONSTRAINT [FK_TABLE__RESTAURANT_BRANCH] FOREIGN KEY([BRANCH_ID])
REFERENCES [dbo].[RESTAURANT_BRANCH] ([BRANCH_ID])
GO
ALTER TABLE [dbo].[TABLE_] CHECK CONSTRAINT [FK_TABLE__RESTAURANT_BRANCH]
GO
ALTER TABLE [dbo].[WORK_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_WORK_HISTORY_EMPLOYEE] FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEE_ID])
GO
ALTER TABLE [dbo].[WORK_HISTORY] CHECK CONSTRAINT [FK_WORK_HISTORY_EMPLOYEE]
GO
ALTER TABLE [dbo].[WORK_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_WORK_HISTORY_RESTAURANT_BRANCH] FOREIGN KEY([BRANCH_ID])
REFERENCES [dbo].[RESTAURANT_BRANCH] ([BRANCH_ID])
GO
ALTER TABLE [dbo].[WORK_HISTORY] CHECK CONSTRAINT [FK_WORK_HISTORY_RESTAURANT_BRANCH]
GO
ALTER DATABASE [susushishi1] SET  READ_WRITE 